"""initial

Revision ID: cc73345a3f00
Revises: 
Create Date: 2026-03-06 08:18:23.103732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc73345a3f00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth__user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'BOARD', 'PARTNER', 'USER', name='auth__role'), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_auth__user_email'), 'auth__user', ['email'], unique=True)
    op.create_table('events__event',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth__user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('messages__conversation',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('GROUP', 'INDIVIDUAL', name='messages__conversation_type'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth__user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('notifications__notification',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('reference_uuid', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth__user.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['auth__user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_notifications__notification_user_uuid'), 'notifications__notification', ['user_uuid'], unique=False)
    op.create_table('events__event_attendee',
    sa.Column('event_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'REJECTED', 'PENDING', name='events__attendee_status'), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth__user.uuid'], ),
    sa.ForeignKeyConstraint(['event_uuid'], ['events__event.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['auth__user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_events__event_attendee_event_uuid'), 'events__event_attendee', ['event_uuid'], unique=False)
    op.create_index(op.f('ix_events__event_attendee_user_uuid'), 'events__event_attendee', ['user_uuid'], unique=False)
    op.create_table('images__album',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('event_uuid', sa.UUID(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth__user.uuid'], ),
    sa.ForeignKeyConstraint(['event_uuid'], ['events__event.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_images__album_event_uuid'), 'images__album', ['event_uuid'], unique=False)
    op.create_table('messages__active_connection',
    sa.Column('conversation_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_uuid'], ['messages__conversation.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['auth__user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_messages__active_connection_conversation_uuid'), 'messages__active_connection', ['conversation_uuid'], unique=False)
    op.create_index(op.f('ix_messages__active_connection_user_uuid'), 'messages__active_connection', ['user_uuid'], unique=False)
    op.create_table('messages__conversation_member',
    sa.Column('conversation_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='messages__member_role'), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_uuid'], ['messages__conversation.uuid'], ),
    sa.ForeignKeyConstraint(['created_by'], ['auth__user.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['auth__user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_messages__conversation_member_conversation_uuid'), 'messages__conversation_member', ['conversation_uuid'], unique=False)
    op.create_index(op.f('ix_messages__conversation_member_user_uuid'), 'messages__conversation_member', ['user_uuid'], unique=False)
    op.create_table('messages__message',
    sa.Column('conversation_uuid', sa.UUID(), nullable=False),
    sa.Column('sender_uuid', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_uuid'], ['messages__conversation.uuid'], ),
    sa.ForeignKeyConstraint(['created_by'], ['auth__user.uuid'], ),
    sa.ForeignKeyConstraint(['sender_uuid'], ['auth__user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_messages__message_conversation_uuid'), 'messages__message', ['conversation_uuid'], unique=False)
    op.create_table('payments__payment',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('event_uuid', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth__user.uuid'], ),
    sa.ForeignKeyConstraint(['event_uuid'], ['events__event.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['auth__user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_payments__payment_event_uuid'), 'payments__payment', ['event_uuid'], unique=False)
    op.create_index(op.f('ix_payments__payment_user_uuid'), 'payments__payment', ['user_uuid'], unique=False)
    op.create_table('images__image',
    sa.Column('album_uuid', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['album_uuid'], ['images__album.uuid'], ),
    sa.ForeignKeyConstraint(['created_by'], ['auth__user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_images__image_album_uuid'), 'images__image', ['album_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images__image_album_uuid'), table_name='images__image')
    op.drop_table('images__image')
    op.drop_index(op.f('ix_payments__payment_user_uuid'), table_name='payments__payment')
    op.drop_index(op.f('ix_payments__payment_event_uuid'), table_name='payments__payment')
    op.drop_table('payments__payment')
    op.drop_index(op.f('ix_messages__message_conversation_uuid'), table_name='messages__message')
    op.drop_table('messages__message')
    op.drop_index(op.f('ix_messages__conversation_member_user_uuid'), table_name='messages__conversation_member')
    op.drop_index(op.f('ix_messages__conversation_member_conversation_uuid'), table_name='messages__conversation_member')
    op.drop_table('messages__conversation_member')
    op.drop_index(op.f('ix_messages__active_connection_user_uuid'), table_name='messages__active_connection')
    op.drop_index(op.f('ix_messages__active_connection_conversation_uuid'), table_name='messages__active_connection')
    op.drop_table('messages__active_connection')
    op.drop_index(op.f('ix_images__album_event_uuid'), table_name='images__album')
    op.drop_table('images__album')
    op.drop_index(op.f('ix_events__event_attendee_user_uuid'), table_name='events__event_attendee')
    op.drop_index(op.f('ix_events__event_attendee_event_uuid'), table_name='events__event_attendee')
    op.drop_table('events__event_attendee')
    op.drop_index(op.f('ix_notifications__notification_user_uuid'), table_name='notifications__notification')
    op.drop_table('notifications__notification')
    op.drop_table('messages__conversation')
    op.drop_table('events__event')
    op.drop_index(op.f('ix_auth__user_email'), table_name='auth__user')
    op.drop_table('auth__user')
    # ### end Alembic commands ###
