# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ConversationType(str, Enum):
    """
    ConversationType
    """

    """
    allowed enum values
    """
    GROUP = 'group'
    INDIVIDUAL = 'individual'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ConversationType from a JSON string"""
        return cls(json.loads(json_str))


