# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from api-client-python.models.order_params1 import OrderParams1
from api-client-python.models.pagination_params1 import PaginationParams1
from api-client-python.models.search_params import SearchParams
from typing import Optional, Set
from typing_extensions import Self

class FiltersInterface(BaseModel):
    """
    Unified filters payload shared by routers, controllers and repositories.
    """ # noqa: E501
    search: Optional[List[SearchParams]] = None
    include_relations: Optional[List[StrictStr]] = None
    pagination: Optional[PaginationParams1] = None
    order: Optional[OrderParams1] = None
    __properties: ClassVar[List[str]] = ["search", "include_relations", "pagination", "order"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FiltersInterface from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in search (list)
        _items = []
        if self.search:
            for _item_search in self.search:
                if _item_search:
                    _items.append(_item_search.to_dict())
            _dict['search'] = _items
        # override the default output from pydantic by calling `to_dict()` of pagination
        if self.pagination:
            _dict['pagination'] = self.pagination.to_dict()
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict['order'] = self.order.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FiltersInterface from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "search": [SearchParams.from_dict(_item) for _item in obj["search"]] if obj.get("search") is not None else None,
            "include_relations": obj.get("include_relations"),
            "pagination": PaginationParams1.from_dict(obj["pagination"]) if obj.get("pagination") is not None else None,
            "order": OrderParams1.from_dict(obj["order"]) if obj.get("order") is not None else None
        })
        return _obj


