# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.api.event_api import EventApi


class TestEventApi(unittest.TestCase):
    """EventApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventApi()

    def tearDown(self) -> None:
        pass

    def test_create_api_events_event_post(self) -> None:
        """Test case for create_api_events_event_post

        Create
        """
        pass

    def test_delete_api_events_event_pk_delete(self) -> None:
        """Test case for delete_api_events_event_pk_delete

        Delete
        """
        pass

    def test_detail_api_events_event_pk_get(self) -> None:
        """Test case for detail_api_events_event_pk_get

        Detail
        """
        pass

    def test_list_api_events_event_get(self) -> None:
        """Test case for list_api_events_event_get

        List
        """
        pass

    def test_register_event_api_events_event_uuid_register_post(self) -> None:
        """Test case for register_event_api_events_event_uuid_register_post

        Register to event
        """
        pass

    def test_unregister_event_api_events_event_uuid_register_delete(self) -> None:
        """Test case for unregister_event_api_events_event_uuid_register_delete

        Unregister from event
        """
        pass

    def test_update_api_events_event_pk_patch(self) -> None:
        """Test case for update_api_events_event_pk_patch

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
