# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.models.list_response_notification import ListResponseNotification

class TestListResponseNotification(unittest.TestCase):
    """ListResponseNotification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListResponseNotification:
        """Test ListResponseNotification
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListResponseNotification`
        """
        model = ListResponseNotification()
        if include_optional:
            return ListResponseNotification(
                items = [
                    api-client-python.models.notification.Notification(
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        uuid = '', 
                        user_uuid = '', 
                        title = '', 
                        body = '', 
                        notification_type = '', 
                        reference_uuid = '', 
                        is_read = True, )
                    ],
                pagination = api-client-python.models.pagination_params.PaginationParams(
                    page = 56, 
                    num_items = 56, 
                    min_page = 56, 
                    max_page = 56, 
                    total_items = 56, ),
                order = api-client-python.models.order_params.OrderParams(
                    attribute = 'uuid', 
                    direction = null, )
            )
        else:
            return ListResponseNotification(
                items = [
                    api-client-python.models.notification.Notification(
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        uuid = '', 
                        user_uuid = '', 
                        title = '', 
                        body = '', 
                        notification_type = '', 
                        reference_uuid = '', 
                        is_read = True, )
                    ],
                pagination = api-client-python.models.pagination_params.PaginationParams(
                    page = 56, 
                    num_items = 56, 
                    min_page = 56, 
                    max_page = 56, 
                    total_items = 56, ),
                order = api-client-python.models.order_params.OrderParams(
                    attribute = 'uuid', 
                    direction = null, ),
        )
        """

    def testListResponseNotification(self):
        """Test ListResponseNotification"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
