# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.models.list_response_conversation import ListResponseConversation

class TestListResponseConversation(unittest.TestCase):
    """ListResponseConversation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListResponseConversation:
        """Test ListResponseConversation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListResponseConversation`
        """
        model = ListResponseConversation()
        if include_optional:
            return ListResponseConversation(
                items = [
                    api-client-python.models.conversation.Conversation(
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        uuid = '', 
                        name = '', 
                        type = null, 
                        image_url = '', )
                    ],
                pagination = api-client-python.models.pagination_params.PaginationParams(
                    page = 56, 
                    num_items = 56, 
                    min_page = 56, 
                    max_page = 56, 
                    total_items = 56, ),
                order = api-client-python.models.order_params.OrderParams(
                    attribute = 'uuid', 
                    direction = null, )
            )
        else:
            return ListResponseConversation(
                items = [
                    api-client-python.models.conversation.Conversation(
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        uuid = '', 
                        name = '', 
                        type = null, 
                        image_url = '', )
                    ],
                pagination = api-client-python.models.pagination_params.PaginationParams(
                    page = 56, 
                    num_items = 56, 
                    min_page = 56, 
                    max_page = 56, 
                    total_items = 56, ),
                order = api-client-python.models.order_params.OrderParams(
                    attribute = 'uuid', 
                    direction = null, ),
        )
        """

    def testListResponseConversation(self):
        """Test ListResponseConversation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
