# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.api.image_api import ImageApi


class TestImageApi(unittest.TestCase):
    """ImageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImageApi()

    def tearDown(self) -> None:
        pass

    def test_create_api_images_image_post(self) -> None:
        """Test case for create_api_images_image_post

        Create
        """
        pass

    def test_delete_api_images_image_pk_delete(self) -> None:
        """Test case for delete_api_images_image_pk_delete

        Delete
        """
        pass

    def test_detail_api_images_image_pk_get(self) -> None:
        """Test case for detail_api_images_image_pk_get

        Detail
        """
        pass

    def test_list_api_images_image_get(self) -> None:
        """Test case for list_api_images_image_get

        List
        """
        pass

    def test_update_api_images_image_pk_patch(self) -> None:
        """Test case for update_api_images_image_pk_patch

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
