# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.api.payment_api import PaymentApi


class TestPaymentApi(unittest.TestCase):
    """PaymentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentApi()

    def tearDown(self) -> None:
        pass

    def test_create_api_payments_payment_post(self) -> None:
        """Test case for create_api_payments_payment_post

        Create
        """
        pass

    def test_delete_api_payments_payment_pk_delete(self) -> None:
        """Test case for delete_api_payments_payment_pk_delete

        Delete
        """
        pass

    def test_detail_api_payments_payment_pk_get(self) -> None:
        """Test case for detail_api_payments_payment_pk_get

        Detail
        """
        pass

    def test_list_api_payments_payment_get(self) -> None:
        """Test case for list_api_payments_payment_get

        List
        """
        pass

    def test_refund_payment_api_payments_payment_uuid_refund_post(self) -> None:
        """Test case for refund_payment_api_payments_payment_uuid_refund_post

        Refund payment
        """
        pass

    def test_update_api_payments_payment_pk_patch(self) -> None:
        """Test case for update_api_payments_payment_pk_patch

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
