# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.models.order_direction import OrderDirection

class TestOrderDirection(unittest.TestCase):
    """OrderDirection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderDirection(self):
        """Test OrderDirection"""
        # inst = OrderDirection()

if __name__ == '__main__':
    unittest.main()
