# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.models.member_role import MemberRole

class TestMemberRole(unittest.TestCase):
    """MemberRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMemberRole(self):
        """Test MemberRole"""
        # inst = MemberRole()

if __name__ == '__main__':
    unittest.main()
