# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.models.conversation_type import ConversationType

class TestConversationType(unittest.TestCase):
    """ConversationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConversationType(self):
        """Test ConversationType"""
        # inst = ConversationType()

if __name__ == '__main__':
    unittest.main()
