# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.models.filters_interface import FiltersInterface

class TestFiltersInterface(unittest.TestCase):
    """FiltersInterface unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FiltersInterface:
        """Test FiltersInterface
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FiltersInterface`
        """
        model = FiltersInterface()
        if include_optional:
            return FiltersInterface(
                search = [
                    api-client-python.models.search_params.SearchParams(
                        attribute = '', 
                        operator = 'eq', 
                        value = null, )
                    ],
                include_relations = [
                    ''
                    ],
                pagination = api-client-python.models.pagination_params.PaginationParams(
                    page = 56, 
                    num_items = 56, 
                    min_page = 56, 
                    max_page = 56, 
                    total_items = 56, ),
                order = api-client-python.models.order_params.OrderParams(
                    attribute = 'uuid', 
                    direction = 'ASC', )
            )
        else:
            return FiltersInterface(
        )
        """

    def testFiltersInterface(self):
        """Test FiltersInterface"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
