# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.models.search_params import SearchParams

class TestSearchParams(unittest.TestCase):
    """SearchParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchParams:
        """Test SearchParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchParams`
        """
        model = SearchParams()
        if include_optional:
            return SearchParams(
                attribute = '',
                operator = 'eq',
                value = None
            )
        else:
            return SearchParams(
                attribute = '',
                operator = 'eq',
        )
        """

    def testSearchParams(self):
        """Test SearchParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
