# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.models.add_member_request import AddMemberRequest

class TestAddMemberRequest(unittest.TestCase):
    """AddMemberRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddMemberRequest:
        """Test AddMemberRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddMemberRequest`
        """
        model = AddMemberRequest()
        if include_optional:
            return AddMemberRequest(
                user_uuid = ''
            )
        else:
            return AddMemberRequest(
                user_uuid = '',
        )
        """

    def testAddMemberRequest(self):
        """Test AddMemberRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
