# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.models.pagination_params import PaginationParams

class TestPaginationParams(unittest.TestCase):
    """PaginationParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationParams:
        """Test PaginationParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationParams`
        """
        model = PaginationParams()
        if include_optional:
            return PaginationParams(
                page = 56,
                num_items = 56,
                min_page = 56,
                max_page = 56,
                total_items = 56
            )
        else:
            return PaginationParams(
        )
        """

    def testPaginationParams(self):
        """Test PaginationParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
