# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.api.conversation_api import ConversationApi


class TestConversationApi(unittest.TestCase):
    """ConversationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConversationApi()

    def tearDown(self) -> None:
        pass

    def test_add_member_api_messages_conversation_uuid_member_post(self) -> None:
        """Test case for add_member_api_messages_conversation_uuid_member_post

        Add member to conversation
        """
        pass

    def test_create_api_messages_conversation_post(self) -> None:
        """Test case for create_api_messages_conversation_post

        Create
        """
        pass

    def test_delete_api_messages_conversation_pk_delete(self) -> None:
        """Test case for delete_api_messages_conversation_pk_delete

        Delete
        """
        pass

    def test_detail_api_messages_conversation_pk_get(self) -> None:
        """Test case for detail_api_messages_conversation_pk_get

        Detail
        """
        pass

    def test_list_api_messages_conversation_get(self) -> None:
        """Test case for list_api_messages_conversation_get

        List
        """
        pass

    def test_remove_member_api_messages_conversation_uuid_member_user_uuid_delete(self) -> None:
        """Test case for remove_member_api_messages_conversation_uuid_member_user_uuid_delete

        Remove member from conversation
        """
        pass

    def test_update_api_messages_conversation_pk_patch(self) -> None:
        """Test case for update_api_messages_conversation_pk_patch

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
