# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_create_api_auth_user_post(self) -> None:
        """Test case for create_api_auth_user_post

        Create
        """
        pass

    def test_delete_api_auth_user_pk_delete(self) -> None:
        """Test case for delete_api_auth_user_pk_delete

        Delete
        """
        pass

    def test_detail_api_auth_user_pk_get(self) -> None:
        """Test case for detail_api_auth_user_pk_get

        Detail
        """
        pass

    def test_list_api_auth_user_get(self) -> None:
        """Test case for list_api_auth_user_get

        List
        """
        pass

    def test_login_api_auth_user_login_post(self) -> None:
        """Test case for login_api_auth_user_login_post

        User login
        """
        pass

    def test_refresh_api_auth_user_refresh_post(self) -> None:
        """Test case for refresh_api_auth_user_refresh_post

        Refresh token
        """
        pass

    def test_register_api_auth_user_register_post(self) -> None:
        """Test case for register_api_auth_user_register_post

        User register
        """
        pass

    def test_update_api_auth_user_pk_patch(self) -> None:
        """Test case for update_api_auth_user_pk_patch

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
