# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.models.order_params import OrderParams

class TestOrderParams(unittest.TestCase):
    """OrderParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderParams:
        """Test OrderParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderParams`
        """
        model = OrderParams()
        if include_optional:
            return OrderParams(
                attribute = 'uuid',
                direction = 'ASC'
            )
        else:
            return OrderParams(
        )
        """

    def testOrderParams(self):
        """Test OrderParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
