# coding: utf-8

"""
    El Triangule API

    REST API for El Triangule

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api-client-python.api.notification_api import NotificationApi


class TestNotificationApi(unittest.TestCase):
    """NotificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationApi()

    def tearDown(self) -> None:
        pass

    def test_create_api_notifications_notification_post(self) -> None:
        """Test case for create_api_notifications_notification_post

        Create
        """
        pass

    def test_delete_api_notifications_notification_pk_delete(self) -> None:
        """Test case for delete_api_notifications_notification_pk_delete

        Delete
        """
        pass

    def test_detail_api_notifications_notification_pk_get(self) -> None:
        """Test case for detail_api_notifications_notification_pk_get

        Detail
        """
        pass

    def test_list_api_notifications_notification_get(self) -> None:
        """Test case for list_api_notifications_notification_get

        List
        """
        pass

    def test_mark_all_read_api_notifications_notification_read_all_patch(self) -> None:
        """Test case for mark_all_read_api_notifications_notification_read_all_patch

        Mark all notifications as read
        """
        pass

    def test_mark_read_api_notifications_notification_uuid_read_patch(self) -> None:
        """Test case for mark_read_api_notifications_notification_uuid_read_patch

        Mark notification as read
        """
        pass

    def test_unread_count_api_notifications_notification_unread_count_get(self) -> None:
        """Test case for unread_count_api_notifications_notification_unread_count_get

        Unread notifications count
        """
        pass

    def test_update_api_notifications_notification_pk_patch(self) -> None:
        """Test case for update_api_notifications_notification_pk_patch

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
