/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddMemberRequest
 */
export interface AddMemberRequest {
    /**
     * 
     * @type {string}
     * @memberof AddMemberRequest
     */
    userUuid: string;
}

/**
 * Check if a given object implements the AddMemberRequest interface.
 */
export function instanceOfAddMemberRequest(value: object): value is AddMemberRequest {
    if (!('userUuid' in value) || value['userUuid'] === undefined) return false;
    return true;
}

export function AddMemberRequestFromJSON(json: any): AddMemberRequest {
    return AddMemberRequestFromJSONTyped(json, false);
}

export function AddMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userUuid': json['user_uuid'],
    };
}

export function AddMemberRequestToJSON(json: any): AddMemberRequest {
    return AddMemberRequestToJSONTyped(json, false);
}

export function AddMemberRequestToJSONTyped(value?: AddMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_uuid': value['userUuid'],
    };
}

