/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Album
 */
export interface Album {
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Album
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Album
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    coverImageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    eventUuid?: string | null;
}

/**
 * Check if a given object implements the Album interface.
 */
export function instanceOfAlbum(value: object): value is Album {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AlbumFromJSON(json: any): Album {
    return AlbumFromJSONTyped(json, false);
}

export function AlbumFromJSONTyped(json: any, ignoreDiscriminator: boolean): Album {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'name': json['name'],
        'coverImageUrl': json['cover_image_url'] == null ? undefined : json['cover_image_url'],
        'eventUuid': json['event_uuid'] == null ? undefined : json['event_uuid'],
    };
}

export function AlbumToJSON(json: any): Album {
    return AlbumToJSONTyped(json, false);
}

export function AlbumToJSONTyped(value?: Album | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by': value['createdBy'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'uuid': value['uuid'],
        'name': value['name'],
        'cover_image_url': value['coverImageUrl'],
        'event_uuid': value['eventUuid'],
    };
}

