/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberRole } from './MemberRole';
import {
    MemberRoleFromJSON,
    MemberRoleFromJSONTyped,
    MemberRoleToJSON,
    MemberRoleToJSONTyped,
} from './MemberRole';

/**
 * 
 * @export
 * @interface ConversationMember
 */
export interface ConversationMember {
    /**
     * 
     * @type {string}
     * @memberof ConversationMember
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ConversationMember
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ConversationMember
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ConversationMember
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof ConversationMember
     */
    conversationUuid: string;
    /**
     * 
     * @type {string}
     * @memberof ConversationMember
     */
    userUuid: string;
    /**
     * 
     * @type {MemberRole}
     * @memberof ConversationMember
     */
    role?: MemberRole;
}



/**
 * Check if a given object implements the ConversationMember interface.
 */
export function instanceOfConversationMember(value: object): value is ConversationMember {
    if (!('conversationUuid' in value) || value['conversationUuid'] === undefined) return false;
    if (!('userUuid' in value) || value['userUuid'] === undefined) return false;
    return true;
}

export function ConversationMemberFromJSON(json: any): ConversationMember {
    return ConversationMemberFromJSONTyped(json, false);
}

export function ConversationMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationMember {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'conversationUuid': json['conversation_uuid'],
        'userUuid': json['user_uuid'],
        'role': json['role'] == null ? undefined : MemberRoleFromJSON(json['role']),
    };
}

export function ConversationMemberToJSON(json: any): ConversationMember {
    return ConversationMemberToJSONTyped(json, false);
}

export function ConversationMemberToJSONTyped(value?: ConversationMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by': value['createdBy'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'uuid': value['uuid'],
        'conversation_uuid': value['conversationUuid'],
        'user_uuid': value['userUuid'],
        'role': MemberRoleToJSON(value['role']),
    };
}

