/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConversationType } from './ConversationType';
import {
    ConversationTypeFromJSON,
    ConversationTypeFromJSONTyped,
    ConversationTypeToJSON,
    ConversationTypeToJSONTyped,
} from './ConversationType';

/**
 * 
 * @export
 * @interface Conversation
 */
export interface Conversation {
    /**
     * 
     * @type {string}
     * @memberof Conversation
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Conversation
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Conversation
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Conversation
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Conversation
     */
    name?: string | null;
    /**
     * 
     * @type {ConversationType}
     * @memberof Conversation
     */
    type?: ConversationType;
    /**
     * 
     * @type {string}
     * @memberof Conversation
     */
    imageUrl?: string | null;
}



/**
 * Check if a given object implements the Conversation interface.
 */
export function instanceOfConversation(value: object): value is Conversation {
    return true;
}

export function ConversationFromJSON(json: any): Conversation {
    return ConversationFromJSONTyped(json, false);
}

export function ConversationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Conversation {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : ConversationTypeFromJSON(json['type']),
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
    };
}

export function ConversationToJSON(json: any): Conversation {
    return ConversationToJSONTyped(json, false);
}

export function ConversationToJSONTyped(value?: Conversation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by': value['createdBy'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'uuid': value['uuid'],
        'name': value['name'],
        'type': ConversationTypeToJSON(value['type']),
        'image_url': value['imageUrl'],
    };
}

