/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    location?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    date?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    time?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    price?: number | null;
}

/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : json['location'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'time': json['time'] == null ? undefined : json['time'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function EventToJSON(json: any): Event {
    return EventToJSONTyped(json, false);
}

export function EventToJSONTyped(value?: Event | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by': value['createdBy'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'uuid': value['uuid'],
        'title': value['title'],
        'description': value['description'],
        'location': value['location'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'time': value['time'],
        'price': value['price'],
    };
}

