/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderParams1 } from './OrderParams1';
import {
    OrderParams1FromJSON,
    OrderParams1FromJSONTyped,
    OrderParams1ToJSON,
    OrderParams1ToJSONTyped,
} from './OrderParams1';
import type { PaginationParams1 } from './PaginationParams1';
import {
    PaginationParams1FromJSON,
    PaginationParams1FromJSONTyped,
    PaginationParams1ToJSON,
    PaginationParams1ToJSONTyped,
} from './PaginationParams1';
import type { SearchParams } from './SearchParams';
import {
    SearchParamsFromJSON,
    SearchParamsFromJSONTyped,
    SearchParamsToJSON,
    SearchParamsToJSONTyped,
} from './SearchParams';

/**
 * Unified filters payload shared by routers, controllers and repositories.
 * @export
 * @interface FiltersInterface
 */
export interface FiltersInterface {
    /**
     * 
     * @type {Array<SearchParams>}
     * @memberof FiltersInterface
     */
    search?: Array<SearchParams>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FiltersInterface
     */
    includeRelations?: Array<string>;
    /**
     * 
     * @type {PaginationParams1}
     * @memberof FiltersInterface
     */
    pagination?: PaginationParams1;
    /**
     * 
     * @type {OrderParams1}
     * @memberof FiltersInterface
     */
    order?: OrderParams1;
}

/**
 * Check if a given object implements the FiltersInterface interface.
 */
export function instanceOfFiltersInterface(value: object): value is FiltersInterface {
    return true;
}

export function FiltersInterfaceFromJSON(json: any): FiltersInterface {
    return FiltersInterfaceFromJSONTyped(json, false);
}

export function FiltersInterfaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiltersInterface {
    if (json == null) {
        return json;
    }
    return {
        
        'search': json['search'] == null ? undefined : ((json['search'] as Array<any>).map(SearchParamsFromJSON)),
        'includeRelations': json['include_relations'] == null ? undefined : json['include_relations'],
        'pagination': json['pagination'] == null ? undefined : PaginationParams1FromJSON(json['pagination']),
        'order': json['order'] == null ? undefined : OrderParams1FromJSON(json['order']),
    };
}

export function FiltersInterfaceToJSON(json: any): FiltersInterface {
    return FiltersInterfaceToJSONTyped(json, false);
}

export function FiltersInterfaceToJSONTyped(value?: FiltersInterface | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'search': value['search'] == null ? undefined : ((value['search'] as Array<any>).map(SearchParamsToJSON)),
        'include_relations': value['includeRelations'],
        'pagination': PaginationParams1ToJSON(value['pagination']),
        'order': OrderParams1ToJSON(value['order']),
    };
}

