/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Image
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Image
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    albumUuid: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    fileUrl: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    thumbnailUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    mediaType?: string;
}

/**
 * Check if a given object implements the Image interface.
 */
export function instanceOfImage(value: object): value is Image {
    if (!('albumUuid' in value) || value['albumUuid'] === undefined) return false;
    if (!('fileUrl' in value) || value['fileUrl'] === undefined) return false;
    return true;
}

export function ImageFromJSON(json: any): Image {
    return ImageFromJSONTyped(json, false);
}

export function ImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Image {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'albumUuid': json['album_uuid'],
        'fileUrl': json['file_url'],
        'thumbnailUrl': json['thumbnail_url'] == null ? undefined : json['thumbnail_url'],
        'mediaType': json['media_type'] == null ? undefined : json['media_type'],
    };
}

export function ImageToJSON(json: any): Image {
    return ImageToJSONTyped(json, false);
}

export function ImageToJSONTyped(value?: Image | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by': value['createdBy'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'uuid': value['uuid'],
        'album_uuid': value['albumUuid'],
        'file_url': value['fileUrl'],
        'thumbnail_url': value['thumbnailUrl'],
        'media_type': value['mediaType'],
    };
}

