/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationParams } from './PaginationParams';
import {
    PaginationParamsFromJSON,
    PaginationParamsFromJSONTyped,
    PaginationParamsToJSON,
    PaginationParamsToJSONTyped,
} from './PaginationParams';
import type { OrderParams } from './OrderParams';
import {
    OrderParamsFromJSON,
    OrderParamsFromJSONTyped,
    OrderParamsToJSON,
    OrderParamsToJSONTyped,
} from './OrderParams';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface ListResponseNotification
 */
export interface ListResponseNotification {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof ListResponseNotification
     */
    items: Array<Notification>;
    /**
     * 
     * @type {PaginationParams}
     * @memberof ListResponseNotification
     */
    pagination: PaginationParams;
    /**
     * 
     * @type {OrderParams}
     * @memberof ListResponseNotification
     */
    order: OrderParams;
}

/**
 * Check if a given object implements the ListResponseNotification interface.
 */
export function instanceOfListResponseNotification(value: object): value is ListResponseNotification {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function ListResponseNotificationFromJSON(json: any): ListResponseNotification {
    return ListResponseNotificationFromJSONTyped(json, false);
}

export function ListResponseNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(NotificationFromJSON)),
        'pagination': PaginationParamsFromJSON(json['pagination']),
        'order': OrderParamsFromJSON(json['order']),
    };
}

export function ListResponseNotificationToJSON(json: any): ListResponseNotification {
    return ListResponseNotificationToJSONTyped(json, false);
}

export function ListResponseNotificationToJSONTyped(value?: ListResponseNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(NotificationToJSON)),
        'pagination': PaginationParamsToJSON(value['pagination']),
        'order': OrderParamsToJSON(value['order']),
    };
}

