/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationParams } from './PaginationParams';
import {
    PaginationParamsFromJSON,
    PaginationParamsFromJSONTyped,
    PaginationParamsToJSON,
    PaginationParamsToJSONTyped,
} from './PaginationParams';
import type { Album } from './Album';
import {
    AlbumFromJSON,
    AlbumFromJSONTyped,
    AlbumToJSON,
    AlbumToJSONTyped,
} from './Album';
import type { OrderParams } from './OrderParams';
import {
    OrderParamsFromJSON,
    OrderParamsFromJSONTyped,
    OrderParamsToJSON,
    OrderParamsToJSONTyped,
} from './OrderParams';

/**
 * 
 * @export
 * @interface ListResponseAlbum
 */
export interface ListResponseAlbum {
    /**
     * 
     * @type {Array<Album>}
     * @memberof ListResponseAlbum
     */
    items: Array<Album>;
    /**
     * 
     * @type {PaginationParams}
     * @memberof ListResponseAlbum
     */
    pagination: PaginationParams;
    /**
     * 
     * @type {OrderParams}
     * @memberof ListResponseAlbum
     */
    order: OrderParams;
}

/**
 * Check if a given object implements the ListResponseAlbum interface.
 */
export function instanceOfListResponseAlbum(value: object): value is ListResponseAlbum {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function ListResponseAlbumFromJSON(json: any): ListResponseAlbum {
    return ListResponseAlbumFromJSONTyped(json, false);
}

export function ListResponseAlbumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseAlbum {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AlbumFromJSON)),
        'pagination': PaginationParamsFromJSON(json['pagination']),
        'order': OrderParamsFromJSON(json['order']),
    };
}

export function ListResponseAlbumToJSON(json: any): ListResponseAlbum {
    return ListResponseAlbumToJSONTyped(json, false);
}

export function ListResponseAlbumToJSONTyped(value?: ListResponseAlbum | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AlbumToJSON)),
        'pagination': PaginationParamsToJSON(value['pagination']),
        'order': OrderParamsToJSON(value['order']),
    };
}

