/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { PaginationParams } from './PaginationParams';
import {
    PaginationParamsFromJSON,
    PaginationParamsFromJSONTyped,
    PaginationParamsToJSON,
    PaginationParamsToJSONTyped,
} from './PaginationParams';
import type { OrderParams } from './OrderParams';
import {
    OrderParamsFromJSON,
    OrderParamsFromJSONTyped,
    OrderParamsToJSON,
    OrderParamsToJSONTyped,
} from './OrderParams';

/**
 * 
 * @export
 * @interface ListResponseUser
 */
export interface ListResponseUser {
    /**
     * 
     * @type {Array<User>}
     * @memberof ListResponseUser
     */
    items: Array<User>;
    /**
     * 
     * @type {PaginationParams}
     * @memberof ListResponseUser
     */
    pagination: PaginationParams;
    /**
     * 
     * @type {OrderParams}
     * @memberof ListResponseUser
     */
    order: OrderParams;
}

/**
 * Check if a given object implements the ListResponseUser interface.
 */
export function instanceOfListResponseUser(value: object): value is ListResponseUser {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function ListResponseUserFromJSON(json: any): ListResponseUser {
    return ListResponseUserFromJSONTyped(json, false);
}

export function ListResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(UserFromJSON)),
        'pagination': PaginationParamsFromJSON(json['pagination']),
        'order': OrderParamsFromJSON(json['order']),
    };
}

export function ListResponseUserToJSON(json: any): ListResponseUser {
    return ListResponseUserToJSONTyped(json, false);
}

export function ListResponseUserToJSONTyped(value?: ListResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(UserToJSON)),
        'pagination': PaginationParamsToJSON(value['pagination']),
        'order': OrderParamsToJSON(value['order']),
    };
}

