/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
    MessageToJSONTyped,
} from './Message';
import type { PaginationParams } from './PaginationParams';
import {
    PaginationParamsFromJSON,
    PaginationParamsFromJSONTyped,
    PaginationParamsToJSON,
    PaginationParamsToJSONTyped,
} from './PaginationParams';
import type { OrderParams } from './OrderParams';
import {
    OrderParamsFromJSON,
    OrderParamsFromJSONTyped,
    OrderParamsToJSON,
    OrderParamsToJSONTyped,
} from './OrderParams';

/**
 * 
 * @export
 * @interface ListResponseMessage
 */
export interface ListResponseMessage {
    /**
     * 
     * @type {Array<Message>}
     * @memberof ListResponseMessage
     */
    items: Array<Message>;
    /**
     * 
     * @type {PaginationParams}
     * @memberof ListResponseMessage
     */
    pagination: PaginationParams;
    /**
     * 
     * @type {OrderParams}
     * @memberof ListResponseMessage
     */
    order: OrderParams;
}

/**
 * Check if a given object implements the ListResponseMessage interface.
 */
export function instanceOfListResponseMessage(value: object): value is ListResponseMessage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function ListResponseMessageFromJSON(json: any): ListResponseMessage {
    return ListResponseMessageFromJSONTyped(json, false);
}

export function ListResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MessageFromJSON)),
        'pagination': PaginationParamsFromJSON(json['pagination']),
        'order': OrderParamsFromJSON(json['order']),
    };
}

export function ListResponseMessageToJSON(json: any): ListResponseMessage {
    return ListResponseMessageToJSONTyped(json, false);
}

export function ListResponseMessageToJSONTyped(value?: ListResponseMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(MessageToJSON)),
        'pagination': PaginationParamsToJSON(value['pagination']),
        'order': OrderParamsToJSON(value['order']),
    };
}

