/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationParams } from './PaginationParams';
import {
    PaginationParamsFromJSON,
    PaginationParamsFromJSONTyped,
    PaginationParamsToJSON,
    PaginationParamsToJSONTyped,
} from './PaginationParams';
import type { OrderParams } from './OrderParams';
import {
    OrderParamsFromJSON,
    OrderParamsFromJSONTyped,
    OrderParamsToJSON,
    OrderParamsToJSONTyped,
} from './OrderParams';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
    ImageToJSONTyped,
} from './Image';

/**
 * 
 * @export
 * @interface ListResponseImage
 */
export interface ListResponseImage {
    /**
     * 
     * @type {Array<Image>}
     * @memberof ListResponseImage
     */
    items: Array<Image>;
    /**
     * 
     * @type {PaginationParams}
     * @memberof ListResponseImage
     */
    pagination: PaginationParams;
    /**
     * 
     * @type {OrderParams}
     * @memberof ListResponseImage
     */
    order: OrderParams;
}

/**
 * Check if a given object implements the ListResponseImage interface.
 */
export function instanceOfListResponseImage(value: object): value is ListResponseImage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function ListResponseImageFromJSON(json: any): ListResponseImage {
    return ListResponseImageFromJSONTyped(json, false);
}

export function ListResponseImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseImage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ImageFromJSON)),
        'pagination': PaginationParamsFromJSON(json['pagination']),
        'order': OrderParamsFromJSON(json['order']),
    };
}

export function ListResponseImageToJSON(json: any): ListResponseImage {
    return ListResponseImageToJSONTyped(json, false);
}

export function ListResponseImageToJSONTyped(value?: ListResponseImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ImageToJSON)),
        'pagination': PaginationParamsToJSON(value['pagination']),
        'order': OrderParamsToJSON(value['order']),
    };
}

