/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Payment } from './Payment';
import {
    PaymentFromJSON,
    PaymentFromJSONTyped,
    PaymentToJSON,
    PaymentToJSONTyped,
} from './Payment';
import type { PaginationParams } from './PaginationParams';
import {
    PaginationParamsFromJSON,
    PaginationParamsFromJSONTyped,
    PaginationParamsToJSON,
    PaginationParamsToJSONTyped,
} from './PaginationParams';
import type { OrderParams } from './OrderParams';
import {
    OrderParamsFromJSON,
    OrderParamsFromJSONTyped,
    OrderParamsToJSON,
    OrderParamsToJSONTyped,
} from './OrderParams';

/**
 * 
 * @export
 * @interface ListResponsePayment
 */
export interface ListResponsePayment {
    /**
     * 
     * @type {Array<Payment>}
     * @memberof ListResponsePayment
     */
    items: Array<Payment>;
    /**
     * 
     * @type {PaginationParams}
     * @memberof ListResponsePayment
     */
    pagination: PaginationParams;
    /**
     * 
     * @type {OrderParams}
     * @memberof ListResponsePayment
     */
    order: OrderParams;
}

/**
 * Check if a given object implements the ListResponsePayment interface.
 */
export function instanceOfListResponsePayment(value: object): value is ListResponsePayment {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function ListResponsePaymentFromJSON(json: any): ListResponsePayment {
    return ListResponsePaymentFromJSONTyped(json, false);
}

export function ListResponsePaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponsePayment {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PaymentFromJSON)),
        'pagination': PaginationParamsFromJSON(json['pagination']),
        'order': OrderParamsFromJSON(json['order']),
    };
}

export function ListResponsePaymentToJSON(json: any): ListResponsePayment {
    return ListResponsePaymentToJSONTyped(json, false);
}

export function ListResponsePaymentToJSONTyped(value?: ListResponsePayment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PaymentToJSON)),
        'pagination': PaginationParamsToJSON(value['pagination']),
        'order': OrderParamsToJSON(value['order']),
    };
}

