/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationParams } from './PaginationParams';
import {
    PaginationParamsFromJSON,
    PaginationParamsFromJSONTyped,
    PaginationParamsToJSON,
    PaginationParamsToJSONTyped,
} from './PaginationParams';
import type { Conversation } from './Conversation';
import {
    ConversationFromJSON,
    ConversationFromJSONTyped,
    ConversationToJSON,
    ConversationToJSONTyped,
} from './Conversation';
import type { OrderParams } from './OrderParams';
import {
    OrderParamsFromJSON,
    OrderParamsFromJSONTyped,
    OrderParamsToJSON,
    OrderParamsToJSONTyped,
} from './OrderParams';

/**
 * 
 * @export
 * @interface ListResponseConversation
 */
export interface ListResponseConversation {
    /**
     * 
     * @type {Array<Conversation>}
     * @memberof ListResponseConversation
     */
    items: Array<Conversation>;
    /**
     * 
     * @type {PaginationParams}
     * @memberof ListResponseConversation
     */
    pagination: PaginationParams;
    /**
     * 
     * @type {OrderParams}
     * @memberof ListResponseConversation
     */
    order: OrderParams;
}

/**
 * Check if a given object implements the ListResponseConversation interface.
 */
export function instanceOfListResponseConversation(value: object): value is ListResponseConversation {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function ListResponseConversationFromJSON(json: any): ListResponseConversation {
    return ListResponseConversationFromJSONTyped(json, false);
}

export function ListResponseConversationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseConversation {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ConversationFromJSON)),
        'pagination': PaginationParamsFromJSON(json['pagination']),
        'order': OrderParamsFromJSON(json['order']),
    };
}

export function ListResponseConversationToJSON(json: any): ListResponseConversation {
    return ListResponseConversationToJSONTyped(json, false);
}

export function ListResponseConversationToJSONTyped(value?: ListResponseConversation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ConversationToJSON)),
        'pagination': PaginationParamsToJSON(value['pagination']),
        'order': OrderParamsToJSON(value['order']),
    };
}

