/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationParams } from './PaginationParams';
import {
    PaginationParamsFromJSON,
    PaginationParamsFromJSONTyped,
    PaginationParamsToJSON,
    PaginationParamsToJSONTyped,
} from './PaginationParams';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';
import type { OrderParams } from './OrderParams';
import {
    OrderParamsFromJSON,
    OrderParamsFromJSONTyped,
    OrderParamsToJSON,
    OrderParamsToJSONTyped,
} from './OrderParams';

/**
 * 
 * @export
 * @interface ListResponseEvent
 */
export interface ListResponseEvent {
    /**
     * 
     * @type {Array<Event>}
     * @memberof ListResponseEvent
     */
    items: Array<Event>;
    /**
     * 
     * @type {PaginationParams}
     * @memberof ListResponseEvent
     */
    pagination: PaginationParams;
    /**
     * 
     * @type {OrderParams}
     * @memberof ListResponseEvent
     */
    order: OrderParams;
}

/**
 * Check if a given object implements the ListResponseEvent interface.
 */
export function instanceOfListResponseEvent(value: object): value is ListResponseEvent {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function ListResponseEventFromJSON(json: any): ListResponseEvent {
    return ListResponseEventFromJSONTyped(json, false);
}

export function ListResponseEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(EventFromJSON)),
        'pagination': PaginationParamsFromJSON(json['pagination']),
        'order': OrderParamsFromJSON(json['order']),
    };
}

export function ListResponseEventToJSON(json: any): ListResponseEvent {
    return ListResponseEventToJSONTyped(json, false);
}

export function ListResponseEventToJSONTyped(value?: ListResponseEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(EventToJSON)),
        'pagination': PaginationParamsToJSON(value['pagination']),
        'order': OrderParamsToJSON(value['order']),
    };
}

