/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MemberRole = {
    Owner: 'owner',
    Member: 'member'
} as const;
export type MemberRole = typeof MemberRole[keyof typeof MemberRole];


export function instanceOfMemberRole(value: any): boolean {
    for (const key in MemberRole) {
        if (Object.prototype.hasOwnProperty.call(MemberRole, key)) {
            if (MemberRole[key as keyof typeof MemberRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MemberRoleFromJSON(json: any): MemberRole {
    return MemberRoleFromJSONTyped(json, false);
}

export function MemberRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberRole {
    return json as MemberRole;
}

export function MemberRoleToJSON(value?: MemberRole | null): any {
    return value as any;
}

export function MemberRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): MemberRole {
    return value as MemberRole;
}

