/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Message
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Message
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    conversationUuid: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    senderUuid: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    content: string;
}

/**
 * Check if a given object implements the Message interface.
 */
export function instanceOfMessage(value: object): value is Message {
    if (!('conversationUuid' in value) || value['conversationUuid'] === undefined) return false;
    if (!('senderUuid' in value) || value['senderUuid'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function MessageFromJSON(json: any): Message {
    return MessageFromJSONTyped(json, false);
}

export function MessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Message {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'conversationUuid': json['conversation_uuid'],
        'senderUuid': json['sender_uuid'],
        'content': json['content'],
    };
}

export function MessageToJSON(json: any): Message {
    return MessageToJSONTyped(json, false);
}

export function MessageToJSONTyped(value?: Message | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by': value['createdBy'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'uuid': value['uuid'],
        'conversation_uuid': value['conversationUuid'],
        'sender_uuid': value['senderUuid'],
        'content': value['content'],
    };
}

