/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    userUuid: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    notificationType: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    referenceUuid?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Notification
     */
    isRead?: boolean;
}

/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
    if (!('userUuid' in value) || value['userUuid'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('notificationType' in value) || value['notificationType'] === undefined) return false;
    return true;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'userUuid': json['user_uuid'],
        'title': json['title'],
        'body': json['body'],
        'notificationType': json['notification_type'],
        'referenceUuid': json['reference_uuid'] == null ? undefined : json['reference_uuid'],
        'isRead': json['is_read'] == null ? undefined : json['is_read'],
    };
}

export function NotificationToJSON(json: any): Notification {
    return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(value?: Notification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by': value['createdBy'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'uuid': value['uuid'],
        'user_uuid': value['userUuid'],
        'title': value['title'],
        'body': value['body'],
        'notification_type': value['notificationType'],
        'reference_uuid': value['referenceUuid'],
        'is_read': value['isRead'],
    };
}

