/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderDirection } from './OrderDirection';
import {
    OrderDirectionFromJSON,
    OrderDirectionFromJSONTyped,
    OrderDirectionToJSON,
    OrderDirectionToJSONTyped,
} from './OrderDirection';

/**
 * Ordering configuration for list endpoints.
 * @export
 * @interface OrderParams
 */
export interface OrderParams {
    /**
     * 
     * @type {string}
     * @memberof OrderParams
     */
    attribute?: string;
    /**
     * 
     * @type {OrderDirection}
     * @memberof OrderParams
     */
    direction?: OrderDirection;
}



/**
 * Check if a given object implements the OrderParams interface.
 */
export function instanceOfOrderParams(value: object): value is OrderParams {
    return true;
}

export function OrderParamsFromJSON(json: any): OrderParams {
    return OrderParamsFromJSONTyped(json, false);
}

export function OrderParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderParams {
    if (json == null) {
        return json;
    }
    return {
        
        'attribute': json['attribute'] == null ? undefined : json['attribute'],
        'direction': json['direction'] == null ? undefined : OrderDirectionFromJSON(json['direction']),
    };
}

export function OrderParamsToJSON(json: any): OrderParams {
    return OrderParamsToJSONTyped(json, false);
}

export function OrderParamsToJSONTyped(value?: OrderParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attribute': value['attribute'],
        'direction': OrderDirectionToJSON(value['direction']),
    };
}

