/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Ordering configuration for list endpoints.
 * @export
 * @interface OrderParams1
 */
export interface OrderParams1 {
    /**
     * 
     * @type {string}
     * @memberof OrderParams1
     */
    attribute?: string;
    /**
     * Allowed ordering directions.
     * @type {OrderParams1DirectionEnum}
     * @memberof OrderParams1
     */
    direction?: OrderParams1DirectionEnum;
}


/**
 * @export
 */
export const OrderParams1DirectionEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type OrderParams1DirectionEnum = typeof OrderParams1DirectionEnum[keyof typeof OrderParams1DirectionEnum];


/**
 * Check if a given object implements the OrderParams1 interface.
 */
export function instanceOfOrderParams1(value: object): value is OrderParams1 {
    return true;
}

export function OrderParams1FromJSON(json: any): OrderParams1 {
    return OrderParams1FromJSONTyped(json, false);
}

export function OrderParams1FromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderParams1 {
    if (json == null) {
        return json;
    }
    return {
        
        'attribute': json['attribute'] == null ? undefined : json['attribute'],
        'direction': json['direction'] == null ? undefined : json['direction'],
    };
}

export function OrderParams1ToJSON(json: any): OrderParams1 {
    return OrderParams1ToJSONTyped(json, false);
}

export function OrderParams1ToJSONTyped(value?: OrderParams1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attribute': value['attribute'],
        'direction': value['direction'],
    };
}

