/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pagination configuration received from the client and returned by the API.
 * @export
 * @interface PaginationParams
 */
export interface PaginationParams {
    /**
     * 
     * @type {number}
     * @memberof PaginationParams
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationParams
     */
    numItems?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationParams
     */
    minPage?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaginationParams
     */
    maxPage?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaginationParams
     */
    totalItems?: number | null;
}

/**
 * Check if a given object implements the PaginationParams interface.
 */
export function instanceOfPaginationParams(value: object): value is PaginationParams {
    return true;
}

export function PaginationParamsFromJSON(json: any): PaginationParams {
    return PaginationParamsFromJSONTyped(json, false);
}

export function PaginationParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationParams {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'numItems': json['num_items'] == null ? undefined : json['num_items'],
        'minPage': json['min_page'] == null ? undefined : json['min_page'],
        'maxPage': json['max_page'] == null ? undefined : json['max_page'],
        'totalItems': json['total_items'] == null ? undefined : json['total_items'],
    };
}

export function PaginationParamsToJSON(json: any): PaginationParams {
    return PaginationParamsToJSONTyped(json, false);
}

export function PaginationParamsToJSONTyped(value?: PaginationParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'num_items': value['numItems'],
        'min_page': value['minPage'],
        'max_page': value['maxPage'],
        'total_items': value['totalItems'],
    };
}

