/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Payment
 */
export interface Payment {
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Payment
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Payment
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    userUuid: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    eventUuid: string;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    paymentMethod: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    transactionId?: string | null;
}

/**
 * Check if a given object implements the Payment interface.
 */
export function instanceOfPayment(value: object): value is Payment {
    if (!('userUuid' in value) || value['userUuid'] === undefined) return false;
    if (!('eventUuid' in value) || value['eventUuid'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    return true;
}

export function PaymentFromJSON(json: any): Payment {
    return PaymentFromJSONTyped(json, false);
}

export function PaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Payment {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'userUuid': json['user_uuid'],
        'eventUuid': json['event_uuid'],
        'amount': json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'paymentMethod': json['payment_method'],
        'status': json['status'] == null ? undefined : json['status'],
        'transactionId': json['transaction_id'] == null ? undefined : json['transaction_id'],
    };
}

export function PaymentToJSON(json: any): Payment {
    return PaymentToJSONTyped(json, false);
}

export function PaymentToJSONTyped(value?: Payment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_by': value['createdBy'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'uuid': value['uuid'],
        'user_uuid': value['userUuid'],
        'event_uuid': value['eventUuid'],
        'amount': value['amount'],
        'currency': value['currency'],
        'payment_method': value['paymentMethod'],
        'status': value['status'],
        'transaction_id': value['transactionId'],
    };
}

