/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Normalized search condition shared across repositories.
 * @export
 * @interface SearchParams
 */
export interface SearchParams {
    /**
     * 
     * @type {string}
     * @memberof SearchParams
     */
    attribute: string;
    /**
     * Allowed operators for search filters.
     * 
     * Declared as an Enum so that:
     * - Pydantic validates the operator value automatically.
     * - FastAPI/OpenAPI exposes it as an enum in the schema, so code generators
     *   create a strongly-typed client.
     * @type {SearchParamsOperatorEnum}
     * @memberof SearchParams
     */
    operator: SearchParamsOperatorEnum;
    /**
     * 
     * @type {any}
     * @memberof SearchParams
     */
    value?: any | null;
}


/**
 * @export
 */
export const SearchParamsOperatorEnum = {
    Eq: 'eq',
    Ne: 'ne',
    Gt: 'gt',
    Gte: 'gte',
    Lt: 'lt',
    Lte: 'lte',
    Like: 'like',
    Ilike: 'ilike',
    Contains: 'contains',
    Icontains: 'icontains',
    In: 'in',
    NotIn: 'not_in',
    IsNull: 'is_null',
    IsNotNull: 'is_not_null'
} as const;
export type SearchParamsOperatorEnum = typeof SearchParamsOperatorEnum[keyof typeof SearchParamsOperatorEnum];


/**
 * Check if a given object implements the SearchParams interface.
 */
export function instanceOfSearchParams(value: object): value is SearchParams {
    if (!('attribute' in value) || value['attribute'] === undefined) return false;
    if (!('operator' in value) || value['operator'] === undefined) return false;
    return true;
}

export function SearchParamsFromJSON(json: any): SearchParams {
    return SearchParamsFromJSONTyped(json, false);
}

export function SearchParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchParams {
    if (json == null) {
        return json;
    }
    return {
        
        'attribute': json['attribute'],
        'operator': json['operator'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function SearchParamsToJSON(json: any): SearchParams {
    return SearchParamsToJSONTyped(json, false);
}

export function SearchParamsToJSONTyped(value?: SearchParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attribute': value['attribute'],
        'operator': value['operator'],
        'value': value['value'],
    };
}

