/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Album,
  FiltersInterface,
  HTTPValidationError,
  ListResponseAlbum,
} from '../models/index';
import {
    AlbumFromJSON,
    AlbumToJSON,
    FiltersInterfaceFromJSON,
    FiltersInterfaceToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListResponseAlbumFromJSON,
    ListResponseAlbumToJSON,
} from '../models/index';

export interface CreateApiImagesAlbumPostRequest {
    album: Album;
}

export interface DeleteApiImagesAlbumPkDeleteRequest {
    pk: string;
}

export interface DetailApiImagesAlbumPkGetRequest {
    pk: string;
    includeRelations?: Array<string> | null;
}

export interface ListApiImagesAlbumGetRequest {
    filters?: FiltersInterface;
}

export interface UpdateApiImagesAlbumPkPatchRequest {
    pk: string;
    body: any | null;
}

/**
 * 
 */
export class AlbumApi extends runtime.BaseAPI {

    /**
     * Creates request options for createApiImagesAlbumPost without sending the request
     */
    async createApiImagesAlbumPostRequestOpts(requestParameters: CreateApiImagesAlbumPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['album'] == null) {
            throw new runtime.RequiredError(
                'album',
                'Required parameter "album" was null or undefined when calling createApiImagesAlbumPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/images/album`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumToJSON(requestParameters['album']),
        };
    }

    /**
     * Create
     */
    async createApiImagesAlbumPostRaw(requestParameters: CreateApiImagesAlbumPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Album>> {
        const requestOptions = await this.createApiImagesAlbumPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlbumFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createApiImagesAlbumPost(requestParameters: CreateApiImagesAlbumPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Album> {
        const response = await this.createApiImagesAlbumPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteApiImagesAlbumPkDelete without sending the request
     */
    async deleteApiImagesAlbumPkDeleteRequestOpts(requestParameters: DeleteApiImagesAlbumPkDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling deleteApiImagesAlbumPkDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/images/album/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete
     */
    async deleteApiImagesAlbumPkDeleteRaw(requestParameters: DeleteApiImagesAlbumPkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteApiImagesAlbumPkDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete
     */
    async deleteApiImagesAlbumPkDelete(requestParameters: DeleteApiImagesAlbumPkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteApiImagesAlbumPkDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for detailApiImagesAlbumPkGet without sending the request
     */
    async detailApiImagesAlbumPkGetRequestOpts(requestParameters: DetailApiImagesAlbumPkGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling detailApiImagesAlbumPkGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeRelations'] != null) {
            queryParameters['include_relations'] = requestParameters['includeRelations'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/images/album/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detail
     */
    async detailApiImagesAlbumPkGetRaw(requestParameters: DetailApiImagesAlbumPkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Album>> {
        const requestOptions = await this.detailApiImagesAlbumPkGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlbumFromJSON(jsonValue));
    }

    /**
     * Detail
     */
    async detailApiImagesAlbumPkGet(requestParameters: DetailApiImagesAlbumPkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Album> {
        const response = await this.detailApiImagesAlbumPkGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listApiImagesAlbumGet without sending the request
     */
    async listApiImagesAlbumGetRequestOpts(requestParameters: ListApiImagesAlbumGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/images/album`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List
     */
    async listApiImagesAlbumGetRaw(requestParameters: ListApiImagesAlbumGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseAlbum>> {
        const requestOptions = await this.listApiImagesAlbumGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseAlbumFromJSON(jsonValue));
    }

    /**
     * List
     */
    async listApiImagesAlbumGet(requestParameters: ListApiImagesAlbumGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseAlbum> {
        const response = await this.listApiImagesAlbumGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateApiImagesAlbumPkPatch without sending the request
     */
    async updateApiImagesAlbumPkPatchRequestOpts(requestParameters: UpdateApiImagesAlbumPkPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling updateApiImagesAlbumPkPatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateApiImagesAlbumPkPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/images/album/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Update
     */
    async updateApiImagesAlbumPkPatchRaw(requestParameters: UpdateApiImagesAlbumPkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Album>> {
        const requestOptions = await this.updateApiImagesAlbumPkPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlbumFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updateApiImagesAlbumPkPatch(requestParameters: UpdateApiImagesAlbumPkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Album> {
        const response = await this.updateApiImagesAlbumPkPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
