/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddMemberRequest,
  Conversation,
  ConversationMember,
  FiltersInterface,
  HTTPValidationError,
  ListResponseConversation,
} from '../models/index';
import {
    AddMemberRequestFromJSON,
    AddMemberRequestToJSON,
    ConversationFromJSON,
    ConversationToJSON,
    ConversationMemberFromJSON,
    ConversationMemberToJSON,
    FiltersInterfaceFromJSON,
    FiltersInterfaceToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListResponseConversationFromJSON,
    ListResponseConversationToJSON,
} from '../models/index';

export interface AddMemberApiMessagesConversationUuidMemberPostRequest {
    uuid: string;
    addMemberRequest: AddMemberRequest;
}

export interface CreateApiMessagesConversationPostRequest {
    conversation: Conversation;
}

export interface DeleteApiMessagesConversationPkDeleteRequest {
    pk: string;
}

export interface DetailApiMessagesConversationPkGetRequest {
    pk: string;
    includeRelations?: Array<string> | null;
}

export interface ListApiMessagesConversationGetRequest {
    filters?: FiltersInterface;
}

export interface RemoveMemberApiMessagesConversationUuidMemberUserUuidDeleteRequest {
    uuid: string;
    userUuid: string;
}

export interface UpdateApiMessagesConversationPkPatchRequest {
    pk: string;
    body: any | null;
}

/**
 * 
 */
export class ConversationApi extends runtime.BaseAPI {

    /**
     * Creates request options for addMemberApiMessagesConversationUuidMemberPost without sending the request
     */
    async addMemberApiMessagesConversationUuidMemberPostRequestOpts(requestParameters: AddMemberApiMessagesConversationUuidMemberPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling addMemberApiMessagesConversationUuidMemberPost().'
            );
        }

        if (requestParameters['addMemberRequest'] == null) {
            throw new runtime.RequiredError(
                'addMemberRequest',
                'Required parameter "addMemberRequest" was null or undefined when calling addMemberApiMessagesConversationUuidMemberPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/messages/conversation/{uuid}/member`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddMemberRequestToJSON(requestParameters['addMemberRequest']),
        };
    }

    /**
     * Add member to conversation
     */
    async addMemberApiMessagesConversationUuidMemberPostRaw(requestParameters: AddMemberApiMessagesConversationUuidMemberPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationMember>> {
        const requestOptions = await this.addMemberApiMessagesConversationUuidMemberPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationMemberFromJSON(jsonValue));
    }

    /**
     * Add member to conversation
     */
    async addMemberApiMessagesConversationUuidMemberPost(requestParameters: AddMemberApiMessagesConversationUuidMemberPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationMember> {
        const response = await this.addMemberApiMessagesConversationUuidMemberPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createApiMessagesConversationPost without sending the request
     */
    async createApiMessagesConversationPostRequestOpts(requestParameters: CreateApiMessagesConversationPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['conversation'] == null) {
            throw new runtime.RequiredError(
                'conversation',
                'Required parameter "conversation" was null or undefined when calling createApiMessagesConversationPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/messages/conversation`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConversationToJSON(requestParameters['conversation']),
        };
    }

    /**
     * Create
     */
    async createApiMessagesConversationPostRaw(requestParameters: CreateApiMessagesConversationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Conversation>> {
        const requestOptions = await this.createApiMessagesConversationPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createApiMessagesConversationPost(requestParameters: CreateApiMessagesConversationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Conversation> {
        const response = await this.createApiMessagesConversationPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteApiMessagesConversationPkDelete without sending the request
     */
    async deleteApiMessagesConversationPkDeleteRequestOpts(requestParameters: DeleteApiMessagesConversationPkDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling deleteApiMessagesConversationPkDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/messages/conversation/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete
     */
    async deleteApiMessagesConversationPkDeleteRaw(requestParameters: DeleteApiMessagesConversationPkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteApiMessagesConversationPkDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete
     */
    async deleteApiMessagesConversationPkDelete(requestParameters: DeleteApiMessagesConversationPkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteApiMessagesConversationPkDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for detailApiMessagesConversationPkGet without sending the request
     */
    async detailApiMessagesConversationPkGetRequestOpts(requestParameters: DetailApiMessagesConversationPkGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling detailApiMessagesConversationPkGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeRelations'] != null) {
            queryParameters['include_relations'] = requestParameters['includeRelations'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/messages/conversation/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detail
     */
    async detailApiMessagesConversationPkGetRaw(requestParameters: DetailApiMessagesConversationPkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Conversation>> {
        const requestOptions = await this.detailApiMessagesConversationPkGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationFromJSON(jsonValue));
    }

    /**
     * Detail
     */
    async detailApiMessagesConversationPkGet(requestParameters: DetailApiMessagesConversationPkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Conversation> {
        const response = await this.detailApiMessagesConversationPkGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listApiMessagesConversationGet without sending the request
     */
    async listApiMessagesConversationGetRequestOpts(requestParameters: ListApiMessagesConversationGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/messages/conversation`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List
     */
    async listApiMessagesConversationGetRaw(requestParameters: ListApiMessagesConversationGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseConversation>> {
        const requestOptions = await this.listApiMessagesConversationGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseConversationFromJSON(jsonValue));
    }

    /**
     * List
     */
    async listApiMessagesConversationGet(requestParameters: ListApiMessagesConversationGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseConversation> {
        const response = await this.listApiMessagesConversationGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeMemberApiMessagesConversationUuidMemberUserUuidDelete without sending the request
     */
    async removeMemberApiMessagesConversationUuidMemberUserUuidDeleteRequestOpts(requestParameters: RemoveMemberApiMessagesConversationUuidMemberUserUuidDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling removeMemberApiMessagesConversationUuidMemberUserUuidDelete().'
            );
        }

        if (requestParameters['userUuid'] == null) {
            throw new runtime.RequiredError(
                'userUuid',
                'Required parameter "userUuid" was null or undefined when calling removeMemberApiMessagesConversationUuidMemberUserUuidDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/messages/conversation/{uuid}/member/{user_uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));
        urlPath = urlPath.replace(`{${"user_uuid"}}`, encodeURIComponent(String(requestParameters['userUuid'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove member from conversation
     */
    async removeMemberApiMessagesConversationUuidMemberUserUuidDeleteRaw(requestParameters: RemoveMemberApiMessagesConversationUuidMemberUserUuidDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.removeMemberApiMessagesConversationUuidMemberUserUuidDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove member from conversation
     */
    async removeMemberApiMessagesConversationUuidMemberUserUuidDelete(requestParameters: RemoveMemberApiMessagesConversationUuidMemberUserUuidDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeMemberApiMessagesConversationUuidMemberUserUuidDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateApiMessagesConversationPkPatch without sending the request
     */
    async updateApiMessagesConversationPkPatchRequestOpts(requestParameters: UpdateApiMessagesConversationPkPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling updateApiMessagesConversationPkPatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateApiMessagesConversationPkPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/messages/conversation/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Update
     */
    async updateApiMessagesConversationPkPatchRaw(requestParameters: UpdateApiMessagesConversationPkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Conversation>> {
        const requestOptions = await this.updateApiMessagesConversationPkPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updateApiMessagesConversationPkPatch(requestParameters: UpdateApiMessagesConversationPkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Conversation> {
        const response = await this.updateApiMessagesConversationPkPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
