/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Event,
  FiltersInterface,
  HTTPValidationError,
  ListResponseEvent,
} from '../models/index';
import {
    EventFromJSON,
    EventToJSON,
    FiltersInterfaceFromJSON,
    FiltersInterfaceToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListResponseEventFromJSON,
    ListResponseEventToJSON,
} from '../models/index';

export interface CreateApiEventsEventPostRequest {
    event: Event;
}

export interface DeleteApiEventsEventPkDeleteRequest {
    pk: string;
}

export interface DetailApiEventsEventPkGetRequest {
    pk: string;
    includeRelations?: Array<string> | null;
}

export interface ListApiEventsEventGetRequest {
    filters?: FiltersInterface;
}

export interface RegisterEventApiEventsEventUuidRegisterPostRequest {
    uuid: string;
}

export interface UnregisterEventApiEventsEventUuidRegisterDeleteRequest {
    uuid: string;
}

export interface UpdateApiEventsEventPkPatchRequest {
    pk: string;
    body: any | null;
}

/**
 * 
 */
export class EventApi extends runtime.BaseAPI {

    /**
     * Creates request options for createApiEventsEventPost without sending the request
     */
    async createApiEventsEventPostRequestOpts(requestParameters: CreateApiEventsEventPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['event'] == null) {
            throw new runtime.RequiredError(
                'event',
                'Required parameter "event" was null or undefined when calling createApiEventsEventPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/events/event`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventToJSON(requestParameters['event']),
        };
    }

    /**
     * Create
     */
    async createApiEventsEventPostRaw(requestParameters: CreateApiEventsEventPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        const requestOptions = await this.createApiEventsEventPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createApiEventsEventPost(requestParameters: CreateApiEventsEventPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.createApiEventsEventPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteApiEventsEventPkDelete without sending the request
     */
    async deleteApiEventsEventPkDeleteRequestOpts(requestParameters: DeleteApiEventsEventPkDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling deleteApiEventsEventPkDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/events/event/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete
     */
    async deleteApiEventsEventPkDeleteRaw(requestParameters: DeleteApiEventsEventPkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteApiEventsEventPkDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete
     */
    async deleteApiEventsEventPkDelete(requestParameters: DeleteApiEventsEventPkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteApiEventsEventPkDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for detailApiEventsEventPkGet without sending the request
     */
    async detailApiEventsEventPkGetRequestOpts(requestParameters: DetailApiEventsEventPkGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling detailApiEventsEventPkGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeRelations'] != null) {
            queryParameters['include_relations'] = requestParameters['includeRelations'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/events/event/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detail
     */
    async detailApiEventsEventPkGetRaw(requestParameters: DetailApiEventsEventPkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        const requestOptions = await this.detailApiEventsEventPkGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Detail
     */
    async detailApiEventsEventPkGet(requestParameters: DetailApiEventsEventPkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.detailApiEventsEventPkGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listApiEventsEventGet without sending the request
     */
    async listApiEventsEventGetRequestOpts(requestParameters: ListApiEventsEventGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/events/event`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List
     */
    async listApiEventsEventGetRaw(requestParameters: ListApiEventsEventGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseEvent>> {
        const requestOptions = await this.listApiEventsEventGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseEventFromJSON(jsonValue));
    }

    /**
     * List
     */
    async listApiEventsEventGet(requestParameters: ListApiEventsEventGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseEvent> {
        const response = await this.listApiEventsEventGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerEventApiEventsEventUuidRegisterPost without sending the request
     */
    async registerEventApiEventsEventUuidRegisterPostRequestOpts(requestParameters: RegisterEventApiEventsEventUuidRegisterPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling registerEventApiEventsEventUuidRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/events/event/{uuid}/register`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Register to event
     */
    async registerEventApiEventsEventUuidRegisterPostRaw(requestParameters: RegisterEventApiEventsEventUuidRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.registerEventApiEventsEventUuidRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Register to event
     */
    async registerEventApiEventsEventUuidRegisterPost(requestParameters: RegisterEventApiEventsEventUuidRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.registerEventApiEventsEventUuidRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for unregisterEventApiEventsEventUuidRegisterDelete without sending the request
     */
    async unregisterEventApiEventsEventUuidRegisterDeleteRequestOpts(requestParameters: UnregisterEventApiEventsEventUuidRegisterDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling unregisterEventApiEventsEventUuidRegisterDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/events/event/{uuid}/register`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Unregister from event
     */
    async unregisterEventApiEventsEventUuidRegisterDeleteRaw(requestParameters: UnregisterEventApiEventsEventUuidRegisterDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.unregisterEventApiEventsEventUuidRegisterDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Unregister from event
     */
    async unregisterEventApiEventsEventUuidRegisterDelete(requestParameters: UnregisterEventApiEventsEventUuidRegisterDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unregisterEventApiEventsEventUuidRegisterDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateApiEventsEventPkPatch without sending the request
     */
    async updateApiEventsEventPkPatchRequestOpts(requestParameters: UpdateApiEventsEventPkPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling updateApiEventsEventPkPatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateApiEventsEventPkPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/events/event/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Update
     */
    async updateApiEventsEventPkPatchRaw(requestParameters: UpdateApiEventsEventPkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        const requestOptions = await this.updateApiEventsEventPkPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updateApiEventsEventPkPatch(requestParameters: UpdateApiEventsEventPkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.updateApiEventsEventPkPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
