/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FiltersInterface,
  HTTPValidationError,
  Image,
  ListResponseImage,
} from '../models/index';
import {
    FiltersInterfaceFromJSON,
    FiltersInterfaceToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ImageFromJSON,
    ImageToJSON,
    ListResponseImageFromJSON,
    ListResponseImageToJSON,
} from '../models/index';

export interface CreateApiImagesImagePostRequest {
    image: Image;
}

export interface DeleteApiImagesImagePkDeleteRequest {
    pk: string;
}

export interface DetailApiImagesImagePkGetRequest {
    pk: string;
    includeRelations?: Array<string> | null;
}

export interface ListApiImagesImageGetRequest {
    filters?: FiltersInterface;
}

export interface UpdateApiImagesImagePkPatchRequest {
    pk: string;
    body: any | null;
}

/**
 * 
 */
export class ImageApi extends runtime.BaseAPI {

    /**
     * Creates request options for createApiImagesImagePost without sending the request
     */
    async createApiImagesImagePostRequestOpts(requestParameters: CreateApiImagesImagePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['image'] == null) {
            throw new runtime.RequiredError(
                'image',
                'Required parameter "image" was null or undefined when calling createApiImagesImagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/images/image`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImageToJSON(requestParameters['image']),
        };
    }

    /**
     * Create
     */
    async createApiImagesImagePostRaw(requestParameters: CreateApiImagesImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Image>> {
        const requestOptions = await this.createApiImagesImagePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createApiImagesImagePost(requestParameters: CreateApiImagesImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Image> {
        const response = await this.createApiImagesImagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteApiImagesImagePkDelete without sending the request
     */
    async deleteApiImagesImagePkDeleteRequestOpts(requestParameters: DeleteApiImagesImagePkDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling deleteApiImagesImagePkDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/images/image/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete
     */
    async deleteApiImagesImagePkDeleteRaw(requestParameters: DeleteApiImagesImagePkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteApiImagesImagePkDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete
     */
    async deleteApiImagesImagePkDelete(requestParameters: DeleteApiImagesImagePkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteApiImagesImagePkDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for detailApiImagesImagePkGet without sending the request
     */
    async detailApiImagesImagePkGetRequestOpts(requestParameters: DetailApiImagesImagePkGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling detailApiImagesImagePkGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeRelations'] != null) {
            queryParameters['include_relations'] = requestParameters['includeRelations'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/images/image/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detail
     */
    async detailApiImagesImagePkGetRaw(requestParameters: DetailApiImagesImagePkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Image>> {
        const requestOptions = await this.detailApiImagesImagePkGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageFromJSON(jsonValue));
    }

    /**
     * Detail
     */
    async detailApiImagesImagePkGet(requestParameters: DetailApiImagesImagePkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Image> {
        const response = await this.detailApiImagesImagePkGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listApiImagesImageGet without sending the request
     */
    async listApiImagesImageGetRequestOpts(requestParameters: ListApiImagesImageGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/images/image`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List
     */
    async listApiImagesImageGetRaw(requestParameters: ListApiImagesImageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseImage>> {
        const requestOptions = await this.listApiImagesImageGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseImageFromJSON(jsonValue));
    }

    /**
     * List
     */
    async listApiImagesImageGet(requestParameters: ListApiImagesImageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseImage> {
        const response = await this.listApiImagesImageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateApiImagesImagePkPatch without sending the request
     */
    async updateApiImagesImagePkPatchRequestOpts(requestParameters: UpdateApiImagesImagePkPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling updateApiImagesImagePkPatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateApiImagesImagePkPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/images/image/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Update
     */
    async updateApiImagesImagePkPatchRaw(requestParameters: UpdateApiImagesImagePkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Image>> {
        const requestOptions = await this.updateApiImagesImagePkPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updateApiImagesImagePkPatch(requestParameters: UpdateApiImagesImagePkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Image> {
        const response = await this.updateApiImagesImagePkPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
