/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FiltersInterface,
  HTTPValidationError,
  ListResponseMessage,
  Message,
} from '../models/index';
import {
    FiltersInterfaceFromJSON,
    FiltersInterfaceToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListResponseMessageFromJSON,
    ListResponseMessageToJSON,
    MessageFromJSON,
    MessageToJSON,
} from '../models/index';

export interface CreateApiMessagesMessagePostRequest {
    message: Message;
}

export interface DeleteApiMessagesMessagePkDeleteRequest {
    pk: string;
}

export interface DetailApiMessagesMessagePkGetRequest {
    pk: string;
    includeRelations?: Array<string> | null;
}

export interface ListApiMessagesMessageGetRequest {
    filters?: FiltersInterface;
}

export interface UpdateApiMessagesMessagePkPatchRequest {
    pk: string;
    body: any | null;
}

/**
 * 
 */
export class MessageApi extends runtime.BaseAPI {

    /**
     * Creates request options for createApiMessagesMessagePost without sending the request
     */
    async createApiMessagesMessagePostRequestOpts(requestParameters: CreateApiMessagesMessagePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['message'] == null) {
            throw new runtime.RequiredError(
                'message',
                'Required parameter "message" was null or undefined when calling createApiMessagesMessagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/messages/message`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessageToJSON(requestParameters['message']),
        };
    }

    /**
     * Create
     */
    async createApiMessagesMessagePostRaw(requestParameters: CreateApiMessagesMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>> {
        const requestOptions = await this.createApiMessagesMessagePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createApiMessagesMessagePost(requestParameters: CreateApiMessagesMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message> {
        const response = await this.createApiMessagesMessagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteApiMessagesMessagePkDelete without sending the request
     */
    async deleteApiMessagesMessagePkDeleteRequestOpts(requestParameters: DeleteApiMessagesMessagePkDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling deleteApiMessagesMessagePkDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/messages/message/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete
     */
    async deleteApiMessagesMessagePkDeleteRaw(requestParameters: DeleteApiMessagesMessagePkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteApiMessagesMessagePkDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete
     */
    async deleteApiMessagesMessagePkDelete(requestParameters: DeleteApiMessagesMessagePkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteApiMessagesMessagePkDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for detailApiMessagesMessagePkGet without sending the request
     */
    async detailApiMessagesMessagePkGetRequestOpts(requestParameters: DetailApiMessagesMessagePkGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling detailApiMessagesMessagePkGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeRelations'] != null) {
            queryParameters['include_relations'] = requestParameters['includeRelations'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/messages/message/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detail
     */
    async detailApiMessagesMessagePkGetRaw(requestParameters: DetailApiMessagesMessagePkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>> {
        const requestOptions = await this.detailApiMessagesMessagePkGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageFromJSON(jsonValue));
    }

    /**
     * Detail
     */
    async detailApiMessagesMessagePkGet(requestParameters: DetailApiMessagesMessagePkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message> {
        const response = await this.detailApiMessagesMessagePkGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listApiMessagesMessageGet without sending the request
     */
    async listApiMessagesMessageGetRequestOpts(requestParameters: ListApiMessagesMessageGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/messages/message`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List
     */
    async listApiMessagesMessageGetRaw(requestParameters: ListApiMessagesMessageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseMessage>> {
        const requestOptions = await this.listApiMessagesMessageGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseMessageFromJSON(jsonValue));
    }

    /**
     * List
     */
    async listApiMessagesMessageGet(requestParameters: ListApiMessagesMessageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseMessage> {
        const response = await this.listApiMessagesMessageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateApiMessagesMessagePkPatch without sending the request
     */
    async updateApiMessagesMessagePkPatchRequestOpts(requestParameters: UpdateApiMessagesMessagePkPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling updateApiMessagesMessagePkPatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateApiMessagesMessagePkPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/messages/message/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Update
     */
    async updateApiMessagesMessagePkPatchRaw(requestParameters: UpdateApiMessagesMessagePkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Message>> {
        const requestOptions = await this.updateApiMessagesMessagePkPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updateApiMessagesMessagePkPatch(requestParameters: UpdateApiMessagesMessagePkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Message> {
        const response = await this.updateApiMessagesMessagePkPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
