/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FiltersInterface,
  HTTPValidationError,
  ListResponseNotification,
  Notification,
} from '../models/index';
import {
    FiltersInterfaceFromJSON,
    FiltersInterfaceToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListResponseNotificationFromJSON,
    ListResponseNotificationToJSON,
    NotificationFromJSON,
    NotificationToJSON,
} from '../models/index';

export interface CreateApiNotificationsNotificationPostRequest {
    notification: Notification;
}

export interface DeleteApiNotificationsNotificationPkDeleteRequest {
    pk: string;
}

export interface DetailApiNotificationsNotificationPkGetRequest {
    pk: string;
    includeRelations?: Array<string> | null;
}

export interface ListApiNotificationsNotificationGetRequest {
    filters?: FiltersInterface;
}

export interface MarkReadApiNotificationsNotificationUuidReadPatchRequest {
    uuid: string;
}

export interface UpdateApiNotificationsNotificationPkPatchRequest {
    pk: string;
    body: any | null;
}

/**
 * 
 */
export class NotificationApi extends runtime.BaseAPI {

    /**
     * Creates request options for createApiNotificationsNotificationPost without sending the request
     */
    async createApiNotificationsNotificationPostRequestOpts(requestParameters: CreateApiNotificationsNotificationPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['notification'] == null) {
            throw new runtime.RequiredError(
                'notification',
                'Required parameter "notification" was null or undefined when calling createApiNotificationsNotificationPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/notifications/notification`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NotificationToJSON(requestParameters['notification']),
        };
    }

    /**
     * Create
     */
    async createApiNotificationsNotificationPostRaw(requestParameters: CreateApiNotificationsNotificationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Notification>> {
        const requestOptions = await this.createApiNotificationsNotificationPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createApiNotificationsNotificationPost(requestParameters: CreateApiNotificationsNotificationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Notification> {
        const response = await this.createApiNotificationsNotificationPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteApiNotificationsNotificationPkDelete without sending the request
     */
    async deleteApiNotificationsNotificationPkDeleteRequestOpts(requestParameters: DeleteApiNotificationsNotificationPkDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling deleteApiNotificationsNotificationPkDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/notifications/notification/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete
     */
    async deleteApiNotificationsNotificationPkDeleteRaw(requestParameters: DeleteApiNotificationsNotificationPkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteApiNotificationsNotificationPkDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete
     */
    async deleteApiNotificationsNotificationPkDelete(requestParameters: DeleteApiNotificationsNotificationPkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteApiNotificationsNotificationPkDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for detailApiNotificationsNotificationPkGet without sending the request
     */
    async detailApiNotificationsNotificationPkGetRequestOpts(requestParameters: DetailApiNotificationsNotificationPkGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling detailApiNotificationsNotificationPkGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeRelations'] != null) {
            queryParameters['include_relations'] = requestParameters['includeRelations'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/notifications/notification/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detail
     */
    async detailApiNotificationsNotificationPkGetRaw(requestParameters: DetailApiNotificationsNotificationPkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Notification>> {
        const requestOptions = await this.detailApiNotificationsNotificationPkGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationFromJSON(jsonValue));
    }

    /**
     * Detail
     */
    async detailApiNotificationsNotificationPkGet(requestParameters: DetailApiNotificationsNotificationPkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Notification> {
        const response = await this.detailApiNotificationsNotificationPkGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listApiNotificationsNotificationGet without sending the request
     */
    async listApiNotificationsNotificationGetRequestOpts(requestParameters: ListApiNotificationsNotificationGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/notifications/notification`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List
     */
    async listApiNotificationsNotificationGetRaw(requestParameters: ListApiNotificationsNotificationGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseNotification>> {
        const requestOptions = await this.listApiNotificationsNotificationGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseNotificationFromJSON(jsonValue));
    }

    /**
     * List
     */
    async listApiNotificationsNotificationGet(requestParameters: ListApiNotificationsNotificationGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseNotification> {
        const response = await this.listApiNotificationsNotificationGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for markAllReadApiNotificationsNotificationReadAllPatch without sending the request
     */
    async markAllReadApiNotificationsNotificationReadAllPatchRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/notifications/notification/read-all`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mark all notifications as read
     */
    async markAllReadApiNotificationsNotificationReadAllPatchRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.markAllReadApiNotificationsNotificationReadAllPatchRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Mark all notifications as read
     */
    async markAllReadApiNotificationsNotificationReadAllPatch(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.markAllReadApiNotificationsNotificationReadAllPatchRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for markReadApiNotificationsNotificationUuidReadPatch without sending the request
     */
    async markReadApiNotificationsNotificationUuidReadPatchRequestOpts(requestParameters: MarkReadApiNotificationsNotificationUuidReadPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling markReadApiNotificationsNotificationUuidReadPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/notifications/notification/{uuid}/read`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mark notification as read
     */
    async markReadApiNotificationsNotificationUuidReadPatchRaw(requestParameters: MarkReadApiNotificationsNotificationUuidReadPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.markReadApiNotificationsNotificationUuidReadPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Mark notification as read
     */
    async markReadApiNotificationsNotificationUuidReadPatch(requestParameters: MarkReadApiNotificationsNotificationUuidReadPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.markReadApiNotificationsNotificationUuidReadPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for unreadCountApiNotificationsNotificationUnreadCountGet without sending the request
     */
    async unreadCountApiNotificationsNotificationUnreadCountGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/notifications/notification/unread-count`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Unread notifications count
     */
    async unreadCountApiNotificationsNotificationUnreadCountGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.unreadCountApiNotificationsNotificationUnreadCountGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Unread notifications count
     */
    async unreadCountApiNotificationsNotificationUnreadCountGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.unreadCountApiNotificationsNotificationUnreadCountGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateApiNotificationsNotificationPkPatch without sending the request
     */
    async updateApiNotificationsNotificationPkPatchRequestOpts(requestParameters: UpdateApiNotificationsNotificationPkPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling updateApiNotificationsNotificationPkPatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateApiNotificationsNotificationPkPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/notifications/notification/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Update
     */
    async updateApiNotificationsNotificationPkPatchRaw(requestParameters: UpdateApiNotificationsNotificationPkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Notification>> {
        const requestOptions = await this.updateApiNotificationsNotificationPkPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updateApiNotificationsNotificationPkPatch(requestParameters: UpdateApiNotificationsNotificationPkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Notification> {
        const response = await this.updateApiNotificationsNotificationPkPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
