/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FiltersInterface,
  HTTPValidationError,
  ListResponsePayment,
  Payment,
} from '../models/index';
import {
    FiltersInterfaceFromJSON,
    FiltersInterfaceToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListResponsePaymentFromJSON,
    ListResponsePaymentToJSON,
    PaymentFromJSON,
    PaymentToJSON,
} from '../models/index';

export interface CreateApiPaymentsPaymentPostRequest {
    payment: Payment;
}

export interface DeleteApiPaymentsPaymentPkDeleteRequest {
    pk: string;
}

export interface DetailApiPaymentsPaymentPkGetRequest {
    pk: string;
    includeRelations?: Array<string> | null;
}

export interface ListApiPaymentsPaymentGetRequest {
    filters?: FiltersInterface;
}

export interface RefundPaymentApiPaymentsPaymentUuidRefundPostRequest {
    uuid: string;
}

export interface UpdateApiPaymentsPaymentPkPatchRequest {
    pk: string;
    body: any | null;
}

/**
 * 
 */
export class PaymentApi extends runtime.BaseAPI {

    /**
     * Creates request options for createApiPaymentsPaymentPost without sending the request
     */
    async createApiPaymentsPaymentPostRequestOpts(requestParameters: CreateApiPaymentsPaymentPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['payment'] == null) {
            throw new runtime.RequiredError(
                'payment',
                'Required parameter "payment" was null or undefined when calling createApiPaymentsPaymentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/payments/payment`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentToJSON(requestParameters['payment']),
        };
    }

    /**
     * Create
     */
    async createApiPaymentsPaymentPostRaw(requestParameters: CreateApiPaymentsPaymentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Payment>> {
        const requestOptions = await this.createApiPaymentsPaymentPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createApiPaymentsPaymentPost(requestParameters: CreateApiPaymentsPaymentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Payment> {
        const response = await this.createApiPaymentsPaymentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteApiPaymentsPaymentPkDelete without sending the request
     */
    async deleteApiPaymentsPaymentPkDeleteRequestOpts(requestParameters: DeleteApiPaymentsPaymentPkDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling deleteApiPaymentsPaymentPkDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/payments/payment/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete
     */
    async deleteApiPaymentsPaymentPkDeleteRaw(requestParameters: DeleteApiPaymentsPaymentPkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteApiPaymentsPaymentPkDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete
     */
    async deleteApiPaymentsPaymentPkDelete(requestParameters: DeleteApiPaymentsPaymentPkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteApiPaymentsPaymentPkDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for detailApiPaymentsPaymentPkGet without sending the request
     */
    async detailApiPaymentsPaymentPkGetRequestOpts(requestParameters: DetailApiPaymentsPaymentPkGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling detailApiPaymentsPaymentPkGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeRelations'] != null) {
            queryParameters['include_relations'] = requestParameters['includeRelations'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/payments/payment/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detail
     */
    async detailApiPaymentsPaymentPkGetRaw(requestParameters: DetailApiPaymentsPaymentPkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Payment>> {
        const requestOptions = await this.detailApiPaymentsPaymentPkGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentFromJSON(jsonValue));
    }

    /**
     * Detail
     */
    async detailApiPaymentsPaymentPkGet(requestParameters: DetailApiPaymentsPaymentPkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Payment> {
        const response = await this.detailApiPaymentsPaymentPkGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listApiPaymentsPaymentGet without sending the request
     */
    async listApiPaymentsPaymentGetRequestOpts(requestParameters: ListApiPaymentsPaymentGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/payments/payment`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List
     */
    async listApiPaymentsPaymentGetRaw(requestParameters: ListApiPaymentsPaymentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponsePayment>> {
        const requestOptions = await this.listApiPaymentsPaymentGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponsePaymentFromJSON(jsonValue));
    }

    /**
     * List
     */
    async listApiPaymentsPaymentGet(requestParameters: ListApiPaymentsPaymentGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponsePayment> {
        const response = await this.listApiPaymentsPaymentGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for refundPaymentApiPaymentsPaymentUuidRefundPost without sending the request
     */
    async refundPaymentApiPaymentsPaymentUuidRefundPostRequestOpts(requestParameters: RefundPaymentApiPaymentsPaymentUuidRefundPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling refundPaymentApiPaymentsPaymentUuidRefundPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/payments/payment/{uuid}/refund`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Refund payment
     */
    async refundPaymentApiPaymentsPaymentUuidRefundPostRaw(requestParameters: RefundPaymentApiPaymentsPaymentUuidRefundPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Payment>> {
        const requestOptions = await this.refundPaymentApiPaymentsPaymentUuidRefundPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentFromJSON(jsonValue));
    }

    /**
     * Refund payment
     */
    async refundPaymentApiPaymentsPaymentUuidRefundPost(requestParameters: RefundPaymentApiPaymentsPaymentUuidRefundPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Payment> {
        const response = await this.refundPaymentApiPaymentsPaymentUuidRefundPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateApiPaymentsPaymentPkPatch without sending the request
     */
    async updateApiPaymentsPaymentPkPatchRequestOpts(requestParameters: UpdateApiPaymentsPaymentPkPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling updateApiPaymentsPaymentPkPatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateApiPaymentsPaymentPkPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/payments/payment/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Update
     */
    async updateApiPaymentsPaymentPkPatchRaw(requestParameters: UpdateApiPaymentsPaymentPkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Payment>> {
        const requestOptions = await this.updateApiPaymentsPaymentPkPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updateApiPaymentsPaymentPkPatch(requestParameters: UpdateApiPaymentsPaymentPkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Payment> {
        const response = await this.updateApiPaymentsPaymentPkPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
