/* tslint:disable */
/* eslint-disable */
/**
 * El Triangule API
 * REST API for El Triangule
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FiltersInterface,
  HTTPValidationError,
  ListResponseUser,
  LoginRequest,
  RefreshRequest,
  RegisterRequest,
  TokenResponse,
  User,
} from '../models/index';
import {
    FiltersInterfaceFromJSON,
    FiltersInterfaceToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListResponseUserFromJSON,
    ListResponseUserToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    RefreshRequestFromJSON,
    RefreshRequestToJSON,
    RegisterRequestFromJSON,
    RegisterRequestToJSON,
    TokenResponseFromJSON,
    TokenResponseToJSON,
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface CreateApiAuthUserPostRequest {
    user: User;
}

export interface DeleteApiAuthUserPkDeleteRequest {
    pk: string;
}

export interface DetailApiAuthUserPkGetRequest {
    pk: string;
    includeRelations?: Array<string> | null;
}

export interface ListApiAuthUserGetRequest {
    filters?: FiltersInterface;
}

export interface LoginApiAuthUserLoginPostRequest {
    loginRequest: LoginRequest;
}

export interface RefreshApiAuthUserRefreshPostRequest {
    refreshRequest: RefreshRequest;
}

export interface RegisterApiAuthUserRegisterPostRequest {
    registerRequest: RegisterRequest;
}

export interface UpdateApiAuthUserPkPatchRequest {
    pk: string;
    body: any | null;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Creates request options for createApiAuthUserPost without sending the request
     */
    async createApiAuthUserPostRequestOpts(requestParameters: CreateApiAuthUserPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling createApiAuthUserPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/user`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserToJSON(requestParameters['user']),
        };
    }

    /**
     * Create
     */
    async createApiAuthUserPostRaw(requestParameters: CreateApiAuthUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.createApiAuthUserPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createApiAuthUserPost(requestParameters: CreateApiAuthUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.createApiAuthUserPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteApiAuthUserPkDelete without sending the request
     */
    async deleteApiAuthUserPkDeleteRequestOpts(requestParameters: DeleteApiAuthUserPkDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling deleteApiAuthUserPkDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/auth/user/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete
     */
    async deleteApiAuthUserPkDeleteRaw(requestParameters: DeleteApiAuthUserPkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteApiAuthUserPkDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete
     */
    async deleteApiAuthUserPkDelete(requestParameters: DeleteApiAuthUserPkDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteApiAuthUserPkDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for detailApiAuthUserPkGet without sending the request
     */
    async detailApiAuthUserPkGetRequestOpts(requestParameters: DetailApiAuthUserPkGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling detailApiAuthUserPkGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeRelations'] != null) {
            queryParameters['include_relations'] = requestParameters['includeRelations'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/auth/user/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detail
     */
    async detailApiAuthUserPkGetRaw(requestParameters: DetailApiAuthUserPkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.detailApiAuthUserPkGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Detail
     */
    async detailApiAuthUserPkGet(requestParameters: DetailApiAuthUserPkGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.detailApiAuthUserPkGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listApiAuthUserGet without sending the request
     */
    async listApiAuthUserGetRequestOpts(requestParameters: ListApiAuthUserGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filters'] != null) {
            queryParameters['filters'] = requestParameters['filters'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/auth/user`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List
     */
    async listApiAuthUserGetRaw(requestParameters: ListApiAuthUserGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseUser>> {
        const requestOptions = await this.listApiAuthUserGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseUserFromJSON(jsonValue));
    }

    /**
     * List
     */
    async listApiAuthUserGet(requestParameters: ListApiAuthUserGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseUser> {
        const response = await this.listApiAuthUserGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginApiAuthUserLoginPost without sending the request
     */
    async loginApiAuthUserLoginPostRequestOpts(requestParameters: LoginApiAuthUserLoginPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling loginApiAuthUserLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/user/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        };
    }

    /**
     * User login
     */
    async loginApiAuthUserLoginPostRaw(requestParameters: LoginApiAuthUserLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        const requestOptions = await this.loginApiAuthUserLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * User login
     */
    async loginApiAuthUserLoginPost(requestParameters: LoginApiAuthUserLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.loginApiAuthUserLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for refreshApiAuthUserRefreshPost without sending the request
     */
    async refreshApiAuthUserRefreshPostRequestOpts(requestParameters: RefreshApiAuthUserRefreshPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['refreshRequest'] == null) {
            throw new runtime.RequiredError(
                'refreshRequest',
                'Required parameter "refreshRequest" was null or undefined when calling refreshApiAuthUserRefreshPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/user/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshRequestToJSON(requestParameters['refreshRequest']),
        };
    }

    /**
     * Refresh token
     */
    async refreshApiAuthUserRefreshPostRaw(requestParameters: RefreshApiAuthUserRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        const requestOptions = await this.refreshApiAuthUserRefreshPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * Refresh token
     */
    async refreshApiAuthUserRefreshPost(requestParameters: RefreshApiAuthUserRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.refreshApiAuthUserRefreshPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerApiAuthUserRegisterPost without sending the request
     */
    async registerApiAuthUserRegisterPostRequestOpts(requestParameters: RegisterApiAuthUserRegisterPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerRequest'] == null) {
            throw new runtime.RequiredError(
                'registerRequest',
                'Required parameter "registerRequest" was null or undefined when calling registerApiAuthUserRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/user/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRequestToJSON(requestParameters['registerRequest']),
        };
    }

    /**
     * User register
     */
    async registerApiAuthUserRegisterPostRaw(requestParameters: RegisterApiAuthUserRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        const requestOptions = await this.registerApiAuthUserRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * User register
     */
    async registerApiAuthUserRegisterPost(requestParameters: RegisterApiAuthUserRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.registerApiAuthUserRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateApiAuthUserPkPatch without sending the request
     */
    async updateApiAuthUserPkPatchRequestOpts(requestParameters: UpdateApiAuthUserPkPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling updateApiAuthUserPkPatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateApiAuthUserPkPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/user/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Update
     */
    async updateApiAuthUserPkPatchRaw(requestParameters: UpdateApiAuthUserPkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.updateApiAuthUserPkPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updateApiAuthUserPkPatch(requestParameters: UpdateApiAuthUserPkPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.updateApiAuthUserPkPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
